{% set version = "1.2.5" %}

package:
  name: seapy
  version: {{ version }}

source:
  url: https://github.com/powellb/seapy/archive/{{ version }}.tar.gz
  sha256: 6928784bd425d490992a53f79c9bf2b890b7c14fb2af64f74fd5fc6791bf5947

build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - meson-python >=0.15.0
    - numpy >=2
    - pip
    - setuptools
  run:
    - python
    - cartopy
    - h5py
    - joblib
    - netcdf4
    - numpy >=1.19.5
    - numpy_groupies
    - rich
    - scipy

test:
  imports:
    - seapy
    - seapy.seawater
    - seapy.roms
    - seapy.model
    - seapy.external.oalib

about:
  home: https://github.com/powellb/seapy/
  license: MIT
  license_file: LICENSE.txt
  summary: State Estimation and Analysis in PYthon

extra:
  recipe-maintainers:
    - ocefpaf
