{% set version = "0.2.0" %}

package:
  name: seapy
  version: {{ version }}

source:
  url: https://github.com/powellb/seapy/archive/{{ version }}.tar.gz
  sha256: 440f2a0171f75988d7df162afdcfc938d2ba2e8b2740cb0ef9a65b7928981d49

build:
  number: 0
  skip: True  # [osx or win or py2k]
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - numpy 1.11.*
    - gcc  # [not win]
  run:
    - python
    - numpy >=1.11
    - scipy
    - joblib
    - h5py
    - netcdf4
    - matplotlib
    - basemap
    - numpy_groupies
    - libgcc  # [not win]

test:
  imports:
    - seapy
    - seapy.seawater
    - seapy.roms
    - seapy.model
    - seapy.external.oalib
    - seapy.external.hindices
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://github.com/powellb/seapy/
  license: MIT
  license_file: LICENSE.txt
  summary: 'State Estimation and Analysis in PYthon'

extra:
  recipe-maintainers:
    - ocefpaf
