{% set version = "0.3.1" %}

package:
  name: seapy
  version: {{ version }}

source:
  url: https://github.com/powellb/seapy/archive/{{ version }}.tar.gz
  sha256: 144fa4d3cd8cb7f80849f52f50497bd74619438bb1097f9f04baecd4680dea6d

build:
  number: 1000
  skip: True  # [osx or win or py2k]
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy 1.14.*
  run:
    - python
    - numpy >=1.14
    - scipy
    - joblib
    - h5py
    - netcdf4
    - matplotlib
    - basemap
    - numpy_groupies

test:
  imports:
    - seapy
    - seapy.seawater
    - seapy.roms
    - seapy.model
    - seapy.external.oalib
    - seapy.external.hindices
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://github.com/powellb/seapy/
  license: MIT
  license_file: LICENSE.txt
  summary: 'State Estimation and Analysis in PYthon'

extra:
  recipe-maintainers:
    - ocefpaf
