{% set version = "0.8.5" %}

package:
  name: seapy
  version: {{ version }}

source:
  url: https://github.com/powellb/seapy/archive/{{ version }}.tar.gz
  sha256: 79c57890c41bbe9735ed44809936f690a6e5c847039205d9350f78a9c877597b

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - flang  # [win and py3k]
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - libflang  # [win and py3k]
    - cartopy
    - h5py
    - joblib
    - netcdf4
    - numpy
    - numpy_groupies
    - rich
    - scipy

test:
  imports:
    - seapy
    - seapy.seawater
    - seapy.roms
    - seapy.model
    - seapy.external.oalib
    - seapy.external.hindices

about:
  home: https://github.com/powellb/seapy/
  license: MIT
  license_file: LICENSE.txt
  summary: State Estimation and Analysis in PYthon

extra:
  recipe-maintainers:
    - ocefpaf
