{% set version = "0.9.9" %}

package:
  name: seapy
  version: {{ version }}

source:
  url: https://github.com/powellb/seapy/archive/{{ version }}.tar.gz
  sha256: af07d552bc3ea8e7936649a1bfe474e914c3099d41e9219461e92d24857cfce7

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - flang  # [win and py3k]
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - libflang  # [win and py3k]
    - cartopy
    - h5py
    - joblib
    - netcdf4
    - numpy
    - numpy_groupies
    - rich
    - scipy

test:
  imports:
    - seapy
    - seapy.seawater
    - seapy.roms
    - seapy.model
    - seapy.external.oalib
    - seapy.external.hindices

about:
  home: https://github.com/powellb/seapy/
  license: MIT
  license_file: LICENSE.txt
  summary: State Estimation and Analysis in PYthon

extra:
  recipe-maintainers:
    - ocefpaf
