{% set version = "1.2" %}

package:
  name: seapy
  version: {{ version }}

source:
  url: https://github.com/powellb/seapy/archive/{{ version }}.tar.gz
  sha256: 8cd0a8b0c464d4b09deb7b9cd34687fcee8bef713bc9092ac7a11d1df48c221a

build:
  number: 1
  skip: True  # [win]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - meson-python >=0.15.0
    - numpy >=2
    - pip
    - setuptools
  run:
    - python
    - cartopy
    - h5py
    - joblib
    - netcdf4
    - numpy
    - numpy_groupies
    - rich
    - scipy

test:
  imports:
    - seapy
    - seapy.seawater
    - seapy.roms
    - seapy.model
    - seapy.external.oalib

about:
  home: https://github.com/powellb/seapy/
  license: MIT
  license_file: LICENSE.txt
  summary: State Estimation and Analysis in PYthon

extra:
  recipe-maintainers:
    - ocefpaf
