appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: NHsm/9nUs97cS3XdPuWQ+jHPxBdu2tAnDDF7EDy1dfxmhKx67dxb/h2eg1pyqkUPaVFwZ9BYdk7XH7KBLm9t9qqevvDwGcLtUlKLHXWjO7aRUKaHpdfZm6j3kxN5GWBHR/5VW1Adghctf97BWxwEfyyCmVpZhiBJc03iJJbql4U2HcxJdseQg4Za4Cd/92GF6THYu79RumwPvCGhVlNjh4pRRUisKhKy5yxai9kqEAtwwiF7BlKBFQ4IBpTCBLS/QH+RlO8bG3/3tzEtLBy5WnCI3oRe6HpLb+PXp7TAeevGvn1D+whsxbZaESTmpovCKXQobtWMYbPXMIZbf9edmMN52hDqEWoAYKReicoKQlGQiW8/m6VWL7b0Bej58UoDAXP4nJa2/jrGNbtYwXjah0sOUxfwGa0niYK55uxCfg9lYh6z80eG6xMfKdzZrIqrXaI7waRLo/8B5Qzl8l28je1nPdcm5nJ7VVyx51u0I+knBPzeY1IUiffyRfIPPjC9fp028FcU+4rZOOrz1+mSRxBTlB8H73v3FOJneq1l/Je05AXnWm0w8g85f5Ei2yi038kG+JMRg6zWXfK5b3ZeKXpZvPZijWtBQFKE7FHdQ9TZ5sC0jIAzTNSZcHCipGQZV/q4aoTqXb+zeGY0sIR/1zl2ZYmpUBx2gkvHzZVS1aI=}
