travis:
  secure:
    BINSTAR_TOKEN: hksyrdvYtJZ8/Ouifu8+PUyL2QVmTOCrrAka9u27Gk29Dym/n7tGwPbM0E3uGairK/AQR1evmq+9fkghJFwbFErA5TCM3gdPPcLf+fqgZdSiLmDtWDrllcnQYGGzKR8z/JDQgmy4Wp8IefbDhLbGf6RlxnpQGDUcbD4sOgC37SIbElJxZLdVeM8ug/LjF+PXxE9Yr633kulbzegRMpqddDjNGkqKPTtyX2/RIAGqU4kUff+dMy+wx0WjKxekVds5DmbZAxCnaG1sedr2HAOaVKzYNzrnAm/PQtro8UkiQ7MdJeTNsfaCCKe0a+j09Dq6XuFfFid4XVDGwTk42EurWAc+eJ32+ckxPPtcvjN1aHY4ScGkGUkF94B+kOOfY0Nrmq60Z68IxCSNOzU1QH5gQ89bJo+WT3cwicHTHHUa+7YOPaZBsoatXzXqxf5kjMWrpIjb98PESwBFDOJWsjocv76k+3e9mXRzIpwMvTlaA0cSYjwXoQ8Y36uejnkZV1ayHU50JButtyeuGnwicfatYFAW6rGXo5myE9GAJo+qRImt4uMUt14o3FFvlfJEUcwH2O+KRXW96484g+tiX+TvGwx6SDbLQQThziTSwy5iPxElqwYETGzPebWydPBCuZqTAfqgSh2B6F6KvX/ohjviAkbfLFE2SrvD4LhCgzZryYY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
