travis:
  secure:
    BINSTAR_TOKEN: QTOEvA3NzuEMeMDO9msiOS8RULgmHc4DJeRSyxLbhVcYcnvIWyrB8CeJyPYSB5tzKLynlW/Z+raT0F69RdYHKJ22rY047g7NlIBAz+5/RwVEET60Dq2YxMhAwZTGeQEKRi3kegaaUY9IemTL1hGAi0WYsXhLdLS/vqhGmsMgnqYvf0ixnR6aDs7MWpg5Kfrt1M2RljrGObWiZiPMFhaeL+lYQZLCCpbCF+vbIHM6dMNGIl+ydYPFB7nh0l4lBt33z1pCUkehANlsw6u/d8GQZyhBjv4owEt1OxbRMfcI/j9AjSeAX+8JIWUzrrhMQN2C2OF8vjUlA4B5NxOsq4fyCuJywIIKLNFPmnscegKdNrA4VgGfGl4fkhJi9j8woArNyu5O2sHzkGWYjyRutaeNNUh0N9JgXdzxaim81G0u+glJzqG6T4Da++z7GgSOjNT/qQpU51+NgtrO3aLOslMB635b2/EDooCUNA0uT9wqxrCqdfSD7m2w83kExt2xKR8g0hIpJ/sxdPMgfZsm6WjXsB80JNb9r+NrbkMF6St5eBDAkuCBCY+uc8WHSt0YZKaW3CX4DgL3SRaLrBFxWt4KacEKM+tbC03mRWAdS1xZaBW151X/OdY/ZWX/LtXb+sZTAtaoEYOxzSyhzRP8navtAMCgcfoICT9v6tKDVhDxPo0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
